import {
  Globe,
  CalendarDays,
  Settings,
  Check,
  SquareKanban,
  ChartGantt,
  List,
  FileText,
  X,
  Plus,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ArrowRight,
  ArrowUp,
  CornerUpLeft,
  Pencil,
  ThumbsUp,
  Trash,
  PanelLeftClose,
  PanelRightClose,
  SquarePen,
  Heading1,
  Heading2,
  Heading3,
  ListOrdered,
  ListTodo,
  ListCollapse,
  Code,
  Minus,
  Database,
  Quote,
  Italic,
} from "lucide-react";

export enum SyncIcons {
  Globe = "Globe",
  CalendarDays = "CalendarDays",
  Settings = "Settings",
  Check = "Check",
  SquareKanban = "SquareKanban",
  ChartGantt = "ChartGantt",
  List = "List",
  FileText = "FileText",
  X = "X",
  Plus = "Plus",
  ChevronLeft = "ChevronLeft",
  ChevronRight = "ChevronRight",
  ChevronDown = "ChevronDown",
  ArrowRight = "ArrowRight",
  ArrowUp = "ArrowUp",
  CornerUpLeft = "CornerUpLeft",
  Pencil = "Pencil",
  ThumbsUp = "ThumbsUp",
  Trash = "Trash",
  PanelLeftClose = "PanelLeftClose",
  PanelRightClose = "PanelRightClose",
  SquarePen = "SquarePen",
  Heading1 = "Heading1",
  Heading2 = "Heading2",
  Heading3 = "Heading3",
  ListOrdered = "ListOrdered",
  ListTodo = "ListTodo",
  ListCollapse = "ListCollapse",
  Code = "Code",
  Minus = "Minus",
  Database = "Database",
  Quote = "Quote",
  Italic = "Italic",
  IconName = "IconName",
}

export const SyncIconMap: Record<SyncIcons, React.FC<{ size?: number; color?: string; strokeWidth?: number }>> = {
  [SyncIcons.Globe]: Globe,
  [SyncIcons.CalendarDays]: CalendarDays,
  [SyncIcons.Settings]: Settings,
  [SyncIcons.Check]: Check,
  [SyncIcons.SquareKanban]: SquareKanban,
  [SyncIcons.ChartGantt]: ChartGantt,
  [SyncIcons.List]: List,
  [SyncIcons.FileText]: FileText,
  [SyncIcons.X]: X,
  [SyncIcons.Plus]: Plus,
  [SyncIcons.ChevronLeft]: ChevronLeft,
  [SyncIcons.ChevronRight]: ChevronRight,
  [SyncIcons.ChevronDown]: ChevronDown,
  [SyncIcons.ArrowRight]: ArrowRight,
  [SyncIcons.ArrowUp]: ArrowUp,
  [SyncIcons.CornerUpLeft]: CornerUpLeft,
  [SyncIcons.Pencil]: Pencil,
  [SyncIcons.ThumbsUp]: ThumbsUp,
  [SyncIcons.Trash]: Trash,
  [SyncIcons.PanelRightClose]: PanelRightClose,
  [SyncIcons.PanelLeftClose]: PanelLeftClose,
  [SyncIcons.SquarePen]: SquarePen,
  [SyncIcons.Heading1]: Heading1,
  [SyncIcons.Heading2]: Heading2,
  [SyncIcons.Heading3]: Heading3,
  [SyncIcons.ListOrdered]: ListOrdered,
  [SyncIcons.ListTodo]: ListTodo,
  [SyncIcons.ListCollapse]: ListCollapse,
  [SyncIcons.Code]: Code,
  [SyncIcons.Minus]: Minus,
  [SyncIcons.Database]: Database,
  [SyncIcons.Quote]: Quote,
  [SyncIcons.Italic]: Italic,
};

type SyncIconProps = {
  name: SyncIcons;
  size?: number;
  color?: string;
  strokeWidth?: number;
};

export const SyncIcon: React.FC<SyncIconProps> = ({
  name,
  size = 24,
  color = "currentColor",
  strokeWidth = 2,
}) => {
  const IconComponent = SyncIconMap[name];
  return <IconComponent size={size} color={color} strokeWidth={strokeWidth} />;
};